### ISSUE TITLE
Multi repo build and push images to Dockerhub

### ISSUE THREAD

**Issue by adibrastegarnia** [werf/werf#1788]
Hi
It looks like werf supports build and push images from multi repos but it is not clear for me how? Suppose we have a multi repos project and we would like to build and push images from those repos to the Dockerhub. Is there any working example that shows how we can achieve the goal using werf? Should we have a central repo that get required files from other repos and build images? 

Thanks

**Comment by distorhead** [comment]
One way is to create a meta project with such a werf.yaml, that will fetch changes from remote repos by specifying `url` param to the git mapping config section:

```
git:
- add: /
  to: /app1
  url: ...
```

https://werf.io/documentation/configuration/stapel_image/git_directive.html

The other way is to use submodules to include some projects into metarepo.

And the third way is to unify all projects into the single repo.

**Comment by distorhead** [comment]
It seems I misunderstood the question in the first place. 

To publish images from multiple projects into the same dockerhub you need to create a repository for each project and then specify option `--images-repo-mode=monorepo` so that multiple images in the each project will be stored in the single repository.
