### ISSUE TITLE
Fix warning: failure using method v2_playbook_on_stats: LiveStdoutListener object has not attribute _reader

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2041]
![image](https://user-images.githubusercontent.com/1161992/72134334-d4684100-3394-11ea-9b08-4f872b65e671.png)

**Comment by distorhead** [comment]
```
• [SLOW TEST:31.071 seconds]
Stapel builder with ansible
  /actions-runner-1/_work/werf/werf/integration/ansible/ansible_test.go:16
  when apt-mark from apt module used (https://github.com/flant/werf/issues/1820)
  /actions-runner-1/_work/werf/werf/integration/ansible/ansible_test.go:109
    should not panic in all supported ubuntu versions
    /actions-runner-1/_work/werf/werf/integration/ansible/ansible_test.go:114
```

**Comment by distorhead** [comment]
Always reproduces on MacOS.

**Comment by diafour** [comment]
Some thoughts and findings:

- Ansible plugin in the main ansible process opens a Unix socket to get stdout and stderr from separate processes of ansible tasks to implement live output.
- `[Errno 36] File name too long` error occurs when plugin opens Unix socket (https://github.com/flant/werf/blob/master/pkg/build/builder/ansible/werf/live_stdout.py#L47)
- There is a limit for a Unix socket path. It should not exceed 108 symbols.
- The path of this Unix socket inside a container is `/.werf/ansible-tmpdir/local/ansible_live_stdout.sock` . Its length is less than 108 symbols.
- But `/.werf/ansible-tmpdir` directory is a bind-mount from host and the real path for the Unix socket on MacOS is this: 
`/private/var/folders/11/qwgcdqwq9w8dc98wc98qwdsaa0000n/T/werf-project-data-456826118/dsb12y44gr/image/deckhouse-controller/ansible-tmpdir-BeforeInstall/local/ansible_live_stdout.sock` — its length is 183 symbols.

- `werf build ... --tmp-dir=/tmp` is not working, because the real path become shorter, but still not enough:
`/private/tmp/werf-project-data-075603826/cuogpr92a2/image/base/ansible-tmpdir-BeforeInstall/local/ansible_live_stdout.sock` — 123 symbols

I see these ways:
1. use additional bind mount for Unix socket and make a temporary path on host shorter.
2. use additional tmpfs mount, for example, into /.werf/ansible-live.
2. use UDP socket. Less coding, but udp is slower.
3. open additional pipe and pass a descriptor to task subprocesses. This may require intervention in a task executor, which was purposely avoided with Unix socket.

**Comment by alexey-igrychev** [comment]
This issue is being closed because the ansible functionality is no longer being developed or supported. This feature has been deprecated and will be removed in version v3. We recommend using the shell directive instead.
