### ISSUE TITLE
A way to cleanup fields from resources in kubernetes

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2224]
There may be fields defined in the kubernetes resource live state, which are not specified in the werf templates. Three way merge cannot remove these fields by design. But there should be a way to indicate to user that these fields exists.

 1. Hardcode all manifest fields that should be checked by werf explicitly: containers, init containers, envs, ...?
 2. Werf should print a WARNING if these fields does not match resource manifest's fields values.

**Comment by ilya-lesikov** [comment]
Mechanics of resource updates changed in a major way in werf v2, since we replaced 3-way merge with Server-Side Apply.

> Werf should print a WARNING if these fields does not match resource manifest's fields values.

This won't happen.

> Hardcode all manifest fields that should be checked by werf explicitly: containers, init containers, envs, ...?

This is not needed.

> Three way merge cannot remove these fields by design. 

Now we can remove some of these fields: those that have field manager set to "kubectl-edit" or those that are in lists or maps that must be overwritten on update, not merged (behavior specified by the resource schema developers).

> But there should be a way to indicate to user that these fields exists.

No need, there are lots of different things (like istio) that can mutate the resource alongside werf and everything will be fine. This is what user expects: we don't touch what we don't own.

Generally solved, not much can be improved at this point.
