### ISSUE TITLE
Shared namespace for multiple deployments support

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2237]
Support deploying multiple applications into the same namespace.

Werf deploy command should write application name to the list of applications deployed into namespace. This list should be stored in the annotation of the namespace resource itself.

Werf dismiss command should delete application name from the list of applications deployed into namespace. When there are no applications left in this namespace — this namespace should be deleted.

There should be an option to keep namespace on dismiss.

`dismiss --with-pvc` option to force deletion of namespaces even if PVC-s are remained in this namespace.

Related to https://github.com/flant/werf/issues/2238.

**Comment by ilya-lesikov** [comment]
Few things to remember:
1. Resources can be deployed in a namespace that is different from release namespace.
2. Resources can be deployed cluster-wide.
3. Issues with atomicity might arise when we mutate the namespace instead of relying on release secrets.

**Comment by ilya-lesikov** [comment]
Probably the only thing that makes sense is to check whether other releases in non-uninstalled state present in the same namespace when `--with-namespace` option specified for `werf dismiss`. If there are other releases, then we should not delete the namespace (return error?).

Other releases should be found the same way `helm list` founds them.

> There should be an option to keep namespace on dismiss.
Default behavior.

> dismiss --with-pvc
No point, since it will delete them anyways (?).

I'm not sure this check is even worth implementing, since when you specify `--with-namespace` it is potentially a very destructive operation, which can remove stateful resources, important secrets, etc. Check for other releases won't help that much, since many resources are created by operators, created automatically as child resources from release resources or created manually. Closing for now.
