### ISSUE TITLE
Is there a way to enable an Image Tag Policy?

### ISSUE THREAD

**Issue by StarpTech** [werf/werf#2694]
Hello,
is there any way to enforce an image tag policy to avoid pulling incompatible changes?
Imagine a microservice architecture. My deployment consists of different applications that follow semver. How can I ensure that no breaking changes are pulled? I would like to lock individual images to patch or minor releases so that fixes can be rollout automatically. Does it make sense?

Example: https://docs.fluxcd.io/en/latest/tutorials/driving-flux/#automations-locks-and-annotations

**Comment by distorhead** [comment]
For example we have a multiple git-repos for each microservice and use GitLab CI/CD. There are 2 jobs to deploy to production environment: converge-production which is automatically runs for every new git-tag and converge-production-manual to run deploy on arbitrary git-tag manually by button. To lock automatic job we have a RELEASE_LOCKED variable.

```
converge-production:
    only:
    - tags
    except:
        variables:
        - $RELEASE_LOCKED == "true"
...

converge-production-manual:
    only:
    - tags
    when: manual
...
```

 - New v3.2.1 has been released
       - Converge-production job deploys new version (sync)
  - New v3.2.2 has been released
       - Converge-production job deploys new version (sync)
 - We detect that v3.2.2 is faulty
 - We set RELEASE_LOCKED=true variable somehow: commit this variable to the gitlab-ci config directly, commit this variable to some file with environment variables which are exported during converge process, set this variable globally in gitlab itself.
 - We go to v3.2.1 tag and hit manual-converge button to rollback

To lock converge-production job to the specific MAJOR.MINOR release we could use more `only`, `except` or `rules` conditions in the job configuration.

## About naming of docker images

Werf uses content-based-tagging as a primary tagging strategy for resulting images names which are built using werf builder. Image tag is some hash that represents the state of the application sources from which this image is built. Werf will redeploy resources that use such images only when this content-based signature has changed. Content based signature changes when a user changes source files of the application in the git or build instructions.

Tagging resulting images by semver now becomes obsolete in werf, because content-based tagging provides much more opportunities to organize a true CI/CD process where changes are often delivered to the production-like environments. Though it is ok to use git-tags together with content-based tagging of images in the werf to organize deploy process itself (we have some recommendations how to organize CI/CD in a different ways https://werf.io/documentation/reference/ci_cd_workflows_overview.html).

Here is the article about content-based-tagging in werf: https://medium.com/flant-com/content-based-tagging-in-werf-eb96d22ac509

**Comment by StarpTech** [comment]
Hi @distorhead thanks for the detailed answer. Unfortunately, you couldn't answer my question. I will try to explain my situation again.

I have `n` repositories not a monorepo, they all belong to the same deployment in Kubernetes. Every repo would exceute `werf` on it's own. Let's say we have:

- API `v1.0.3` (Team-A)
- Frontend `v1.2.0` (Team-B)
- Identity server `v1.5.1` (Team-C)

In the meantime, Team A has released a new version of the API `v2.0.0`.

- API `v2.0.0` (Production branch)
- Frontend `v1.2.x` (Production branch)
- Identity server `v1.5.x` (Production branch)

First question, where do I configure that this setup belongs to the same deployment? I'd assume that the kubernetes deployment manifest must exist in all repositories? (werf will replace the tag and rollout a new deployment) How do you handle that duplication? Helm chart?

While this approach would work great in Production it's not great for spawning PR preview deployments because I'd need to configure the specific version matrix manually before creating the PR. (Question beside: Is it possible to do it?)

Wouldn't it be much easier if I could lock for patch only? Then after every commit on my PR I could update my kubernetes deployment and pull all other dependencies in a `pullImagePolicy: latest` like policy.

Does it make sense?

**Comment by distorhead** [comment]
Hi! I would try to answer more.

## Using werf from multiple projects

It is ok to use werf from multiple independent projects, yet deploy to the same deployment in the kubernetes as follows:

 - You will need same shared kube-config setup for each project.
 - You will need same shared set of kubernetes namespaces (per environment, for example: production, staging, multiple review environment namespaces).
   - Each project can be deployed into production, staging of some review kubernetes shared namespace.
 - Each project defines own chart in the repo (`.helm` dir) with own kubernetes resource templates.
 - Microservices use persistent dns names do discover each other:
   - Each project defines own Service kubernetes resource.
 - CI/CD of each project is independent and responsible for this service to be available all the time in selected environment.
 - There should be no conflicts related to the kubernetes configuration between projects.
 - There may be some common configuration, that all project share — this can be stored in the ConfigMaps or Secrets. 
   - There may be shared helm-values — these will be copied between projects, but usually there are no shared values.
 - As each project defines own helm-chart, each project also deploys own helm-release during werf-deploy-process (names of releases will differ).

This scheme represent a decentralized CI/CD of kubernetes deployment.

## Deployment using chart-repository

We are also working on the other way of deployment of microservices using chart-repository.

 - Each project will have ability to deploy release for some environment **not** directly into kubernetes cluster deployment, but into so called chart-repository (implementation details: chart-repo will be located in the docker-registry).
 - The point is: CI/CD of each microservice project will no longer be responsible for deployment directly into kubernetes, it will be responsible only for making new version publicly available via chart-repository.
 - Then this chart can be deployed from chart-repository into kubernetes cluster by some centralized CI/CD.

Ability to deploy using chart-repository will be available in the next big version v1.2 (current version is v1.1).

## About preview environments in decentralized CI/CD

Preview envrionment can be defined by kubernetes namespace (dns-names do discover microservices are based on the kubernetes namespace and some statical names of each microservice (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services)). Then we could configure review environments as follows:

 - CI/CD of each project should be set up so that `review-SOME_NAME` git branches will be deployed into `review-SOME_NAME` kubernetes namespace.
 - To deploy microservice API v2.0.0 to the review environment we could create a special git-branch, called `review-new-api`.
 - Go to the each microservice project and create a branch called `review-new-api` and hit deploy in your CI/CD, or your CI/CD could automatically deploy microservice to the review environment when it sees that git-branch by `review-SOME_NAME` template has been created/updated.

## Auto deploy of patch releases and locking

Given that our CI/CD setup is decentralized, each project would use CI/CD system for automatic deployments when a new version of project arrives.

I think it is better to use git-tag names or git-branch names to control your CI/CD and not use docker-images names. In other words create git-tag called v2.0.0 for your API project and configure CI/CD to detect new git-tags and git-branches, and perform automatic deployments when new patch release available or whatever. 

Because we suppose that git is the single source of truth, not a docker-registry. Furthermore werf uses another scheme of naming of docker images using content based signatures. Your microservice could use one or multiple docker images in general, and not all of these images should be rebuilt, retagged and later redeployed with downtime when new version of microservice has been released. It is better to decouple version of docker images from the version of the application.

As for `imagePullPolicy=Always` analogy, I think parsing of git-branch names and git-tags could solve this problem: run CI/CD deploy pipeline when a new commit has arrived into your branch (named as `review-SOME_NAME` or smth) and decide whether you should autodeploy new version or not.

---

P.S. We really want to help with your deployment, feel free to ask more questions.

**Comment by StarpTech** [comment]
Hi! Thanks for the bunch of information. It was very helpful to rethink my approach. Based on the multirepo approach, I would need to publish all helm charts of all projects and use them to bootstrap my preview environment on a dedicated branch. This could happen e.g in a feature branch of the `frontend` project.

How will werf support this process? I think werf can only operate in a single repository context?
How to reference to multiple helm charts?

I think, I'd need to define my expected environment in another local chart template? If so, 

If so, I'd still need to define maintain a specific version of my `frontend` project in the helm chart.

In order to avoid managing such a version. It would be great to lock to `API 1.x.x` so werf can build and deploy my new environment.

Something like this. `werf` must be able to determine the right image version based on the semver constraint.

```
project: my-project
configVersion: 1
---
image: app
from: java:8-jdk-alpine
lock: 1.x.x
```

Open PR:
```
werf build-and-publish --tag-git-branch=feature/my-new-feature
werf deploy --env=preview --release=feature/my-new-feature --helm-chart-dir=preview-environment
```
Closing PR:
```
werf dismiss --release feature/my-new-feature --with-namespace
```

`preview-environment` includes the deployments for both services.

**Comment by StarpTech** [comment]
@distorhead is it clear now what I'm trying to propose ?

**Comment by distorhead** [comment]
Hello! Sorry for delayed response.

Werf cannot be used to publish helm chart into chart repository yet in the current v1.1 version. But we are working on the v1.2 version which will be able to do this. Also v1.1 version does not support werf-projects to be used as subcharts in another werf-project (v1.2 will also have this ability). 

> I think I'd need to define my expected environment in another local chart template and use the other as sub-charts?
> ...
> In order to avoid managing such a version. It would be great to lock to my external service to API 1.x.x.

I think this is good feature for werf to be able to lock external service from chart repo by some semver-based constraint. We will certainly consider this feature when implementing publishing of werf-charts into chart repo (which will be soon). v1.2 will be usable in october I think.

**Comment by StarpTech** [comment]
@distorhead thanks.

**Comment by distorhead** [comment]
@StarpTech Hi!

Happy to announce that werf v1.2 ea channel now contains basic bundles functionality:

 - `werf bundle publish` (publish into container registry);
 - `werf bundle apply` (deploy published bundle into k8s);
 - `werf bundle export` (publish bundle into dir);
 - `werf bundle download` (download published bundle into dir).

Bundle is a collection of helm chart files + built images + provided values. This collection published into container registry by the `werf bundle publish` command. Then this collection can be applied by the `werf bundle apply` command, apply command does not need original project files it only needs an address of the container registry repo and version tag, because bundle contains all needed files and related images to be deployed into k8s cluster.

**Back to the point**. Bundles are published by some tag, which can be `latest`, some arbitrary symbolic tag or SEMVER. When using `latest` or another static tag bundle-apply command will automatically perform update if newer bundle version has been published by this tag.

There is no ability to autoupdate by semver constraints yet, separate issue for this feature: https://github.com/werf/werf/issues/3169. So I am closing current issue in favor of the specified issue.

**Comment by StarpTech** [comment]
@distorhead thanks for the update!
