### ISSUE TITLE
Running werf in buildah mode in containers and Kubernetes

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#3933]

**Comment by ilya-lesikov** [comment]
Done, soon lands in all releases up to the stable release channel.

What's done:
* Now WERF_BUILDAH_MODE env var used instead of WERF_CONTAINER_RUNTIME_BUILDAN to set Buidah mode/isolation. `WERF_BUILDAH_MODE="auto"` is enough to enable builds with Buildah, without Docker.
* _native-chroot_ Buildah mode is the only mode available in containers.
* Only Linux: _native-rootless_ (oci) mode now used by the default if not in a container (previously _native-chroot_). For macOS/Windows the same _docker-with-fuse_ mode is used.
* VFS storage driver available in addition to OverlayFS. Any OS, any mode, containerized or not. To enable: `WERF_BUILDAH_STORAGE_DRIVER=vfs`
* Preconfigured images with werf provided to run werf in containers/Kubernetes. Based on Alpine, Ubuntu and CentOS. `ghcr.io/werf/werf:1.2-(alpha|beta|ea|stable)-(alpine|ubuntu|centos)`
* If native kernel OverlayFS support is available it is used automatically. If not hen `fuse-overlayfs` will be used.
* Now you can run werf in unprivileged containers/Pods.
* Documentation added to explain how to run werf in Kubernetes/containers and how to integrate it with your CI.
