### ISSUE TITLE
werf.exe on windows requires user right that is normally missing from an ordinary user

### ISSUE THREAD

**Issue by LevT2** [werf/werf#4051]
The issue is creating symlinks: 
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links

Using elevated terminal is a workaround but it is redundant. Found an (ugly) solution for automated security policy modification:
https://stackoverflow.com/questions/20627445/how-to-assign-user-rights-to-a-local-user-account-through-powershell

**Comment by ilya-lesikov** [comment]
I guess we need to add instructions for how to grant this permission in the werf installation docs for Windows. On the other side, this is expected behavior as of now #1925

The next step would be either avoiding creating symlinks on Windows altogether or granting this permission automatically to the user by the planned werf installer for Windows (which is not in work yet).

Instructions for Windows are already present here https://werf.io/guides/rails/100_basic/10_build.html#preliminary-steps, we need to move them to the installation page.

**Comment by ilya-lesikov** [comment]
Workaround moved here: https://werf.io/getting_started/?usage=localDev&os=windows&buildBackend=docker

Will close this issue as a duplicate of #1925
