### ISSUE TITLE
Add artifacts exporter

### ISSUE THREAD

**Issue by n-bes** [werf/werf#4576]
Hi, I want to use ```werf``` as ```docker``` replacement. My typical scenario is _to build an image and extract files_:

```Dockerfile
FROM ubuntu as builder
WORKDIR /
RUN echo hello > world.txt 

FROM scratch as builder_export
COPY --from=builder world.txt /
```

```sh
docker --build . --target builder_export --output result_directory
```
```--output``` described in [docs](https://docs.docker.com/engine/reference/commandline/build/#custom-build-outputs)

@alexey-igrychev [provides](https://t.me/werf_ru/23856) a workaround:
```sh
docker create --name CONTAINER_NAME IMAGE_NAME
docker cp CONTAINER_NAME:CONTAINER_PATH HOST_PATH
docker rm CONTAINER_NAME
```
It requires 3 additional steps.

@ilya-lesikov [provides](https://t.me/werf_ru/24394) a solution with ```kube-run```
```
werf kube-run image1 --copy-from "/from/container:to/localhost" -- command
```
It requires k8s.

Could you implement one-line exporter without ```k8s```?

**Comment by ilya-lesikov** [comment]
Hello, our focus is on delivery to K8s and we aren't considering werf (or its part) as an alternative to Docker. To be honest, we are planning to drop any dependency on Docker probably in the next minor release since K8s is deprecated Docker as a container runtime and we are striving to be K8s-centric. So, unfortunately, this is to be out of scope for werf as of now.
