### ISSUE TITLE
Add "upgrade only" option for converge

### ISSUE THREAD

**Issue by CRASH-Tech** [werf/werf#5329]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

subj

**Comment by distorhead** [comment]
@CRASH-Tech Hi!

I've just refreshed your case described in the TG chat. It sound like:

* There are multiple kubernetes clusters.
* First version of an application deployed manually into certain cluster.
* Then we set up an argocd application with some werf integration, which calls 'werf converge' to just upgrade the application.

And to exclude configuration errors in such case it would be convenient to tell werf to fail if no deployed application found — 'upgrade only' option for 'werf converge'.

I think we could add such option.

**Comment by distorhead** [comment]
Created a draft for `--require-deployed` option (by analogy with existing `--require-build-images` option): https://github.com/werf/werf/pull/5713

**Comment by distorhead** [comment]
@CRASH-Tech Hi!

I have to say that unfortunately we've decided to reject [current pull request](https://github.com/werf/werf/issues/5329) and this feature completely.

The reasons are:
1. From the beginning of werf project we use "declarative" mode for converge/deploy command: this command should converge kubernetes cluster to the state when "application exists and running", and it doesn't matter existed application release before command execution or not, no external factor affects converge behaviour. In werf 1.1 and 1.2 that use helm 2 or 3 it implies usage of `upgrade --install` command without options. The same logic with `werf dismiss`: application release should not exist after command execution.
2. There is a new deploy engine ([called nelm](https://github.com/werf/nelm)) in the final stage of development right now. And we are on a way to completely switch to this engine instead of helm 3 in the 1.2 version. And this new engine not supposed to work in a "upgrade only" or "upgrade --install" modes, it is designed to always work in a "application exists and running after deploy" mode, and we are currently see no reason in implementing these old undesired helm modes.

So if we merge [this pull request](https://github.com/werf/werf/issues/5329) then we have to implement this feature for a new deploy engine also, but it is currently undesireable due to (2).

As for your case, when you need to prevent deployment into the fresh environment due to lost or broken kubeconfig there is another workaround: just check helm release existance with `werf helm status RELEASE -n NAMESPACE` before calling `werf converge`.
