### ISSUE TITLE
Warning on update werf

### ISSUE THREAD

**Issue by dozer111** [werf/werf#5347]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

v1.2.197+fix5

### How to reproduce

`trdl update werf 1.2 stable`

### Result

Warning triggers:

`WARNING: Self-update failed: unable to init tuf client: unable to init file local store: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-001809]`

Werf is still v1.2.197+fix5

### Expected result

werf would update to latest version

### Additional information

ubuntu 20.04

**Comment by alexey-igrychev** [comment]
Thank you for your feedback.

The latest version of the stable channel is up-to-date in your case (https://github.com/werf/werf/blob/main/trdl_channels.yaml#L40-L41).

The warning says the trdl self-update procedure failed due to corrupted local storage. It is a known leveldb issue that can be fixed by readding the trdl repository. Remove the trdl repository from the trdl configuration and run trdl command again:

```
yq -i 'del(.repositories[] | select(.name == "trdl"))' ~/.trdl/config.yaml
trdl update werf 1.2 stable
```
