### ISSUE TITLE
Consistent use of --insecure-registry and --skip-tls-verify-registry flag in all commands

### ISSUE THREAD

**Issue by ryou90** [werf/werf#6393]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

I would like to login into a private gitlab instance. This uses a self-signed certificate.
Therefore, the error 

> tls: failed to verify certificate: x509

 appears, which is also clear to me, since it was not issued publicly.
It would be helpful if the flag --skip-tls-verify-registry was also available in this case.

### Solution (if you have one)

 Add --skip-tls-verify-registry flag to _werf cr_ command

### Additional information

It would be nice to add this flag also to _werf helm registry login_

**Comment by ryou90** [comment]
I noticed that _--insecure-registry_ solves my problem at this point. But the flag should actually be there to accept http connections.

Recommendation: Change the description, or standardize the flag everywhere.
_--insecure-registry_ and _--skip-tls-verify-registry_ seem to be used differently depending on the command

**Comment by alexey-igrychev** [comment]
Hello! Thank you for your feedback.

We acknowledge that there’s currently some confusion regarding registry options in werf. The main werf commands support both `--insecure-registry` and `--skip-tls-verify-registry` flags. However, werf cr login does not include the `--skip-tls-verify-registry` flag because it relies on the Docker CLI code, which currently does not support this behavior (see more here: https://github.com/docker/cli/issues/3183).

We are considering implementing ORAS to add this functionality. However, one of the reasons why Docker CLI has not added this option is that it would require specifying security flags for each operation, not just during login.

We prefer to avoid changing the original command interface for `werf helm registry login`. In this case, we recommend using `werf cr login`, which is more suitable for registry operations working with werf.

Thank you for your suggestion and attention to detail!

**Comment by alexey-igrychev** [comment]
rel https://github.com/werf/werf/discussions/6167

**Comment by ryou90** [comment]
Thx for your clarification.

I think this Issue can be closed for now
